name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slash_command_dispatch:
    runs-on: ubuntu-20.04
    steps:
      - name: Print inputs 🖨️
        run: echo "${{ toJson(github.event.issue) }}"

      # https://github.com/peter-evans/slash-command-dispatch
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          reaction-token: ${{ secrets.GH_PERSONAL_TOKEN }}
          dispatch-type: workflow
          static-args: |
            ref=origin/pull/${{ github.event.issue.number }}/merge
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
          # we only have a single "/cypress" command in this repo
          commands: |
            cypress
