name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slash_command_dispatch:
    runs-on: ubuntu-20.04
    steps:
      - name: Print inputs 🖨️
        run: echo "${{ toJson(github.event.issue) }}"

      # we only know the pull request number, like 12, 20, etc
      # but to trigger the workflow we need the branch name
      # https://github.com/bahmutov/get-branch-name-by-pr
      - name: Find the PR branch name 🔎
        uses: bahmutov/get-branch-name-by-pr@v1
        id: pr
        with:
          repo-token: ${{ secrets.GH_PERSONAL_TOKEN }}
          pr-id: ${{ github.event.issue.number }}

      # https://github.com/peter-evans/slash-command-dispatch
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          reaction-token: ${{ secrets.GH_PERSONAL_TOKEN }}
          dispatch-type: workflow
          static-args: |
            ref=${{ steps.pr.outputs.branch }}
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
          # we only have a single "/cypress" command in this repo
          commands: |
            cypress
